yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('500/', views.server_error, name='500'),
    path('404/', views.page_not_found, name='404'),
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.create_post, name='create_post'),
    path('posts/<int:post_id>/edit/',
         views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'auth/password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change_form'
    ),
    path(
        'auth/password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_changa_done.html'),
        name='password_change_done'
    ),
    path(
        'auth/password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'auth/password_reset/done',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'auth/reset/<uidb64>/<token>',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_comfirm'
    ),
    path(
        'auth/reset/done',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler403, handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("about/", include("about.urls", namespace='about')),
    path("", include("posts.urls", namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa
handler403 = "posts.views.forbidden"  # noqa

yatube/templates/includes/add_comment.html
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %} 

yatube/templates/includes/author_part.html
<div class="col-md-3 mb-3 mt-1">
  <div class="card">
    <div class="card-body">
      <div class="h2">{{ author.get_full_name }}</div>
      <div class="h3 text-muted">
        <a href="{% url 'posts:profile' author.username %}">@{{ author.username }}</a>
      </div>
      <div class="mt-3"></div>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"></li>
      <li class="list-group-item">
        <div class="h6 text-muted">Записей: {{ author.posts.count }}</div>
      </li>
    </ul>
  </div>
</div>

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightpink">
  <div class="container">
    <a class="navbar-brand" href="{% url "posts:index" %}">
      <img src="{% static "img/logo.png" %}"
           width="30"
           height="30"
           class="d-inline-block align-top"
           alt="">
      <span style="color:red">Ya</span>tube
  </a>
  <ul class="nav nav-pills">
    {% with request.resolver_match.view_name as view_name %}
      <li class="nav-item">
        <a class="nav-link {% if view_name  == "about:author" %}active{% endif %}"
           href="{% url "about:author" %}">
          Об авторе
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == "about:tech" %}active{% endif %}"
           href="{% url "about:tech" %}">Технологии</a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == "posts:create_post" %}active{% endif %}"
             href="{% url "posts:create_post" %}">Новая запись</a>
        </li>
        <li class="nav-item">
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == "users:password_change_form" %}active{% endif %}"
               href="{% url "users:password_change_form" %}">Изменить пароль</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == "users:logout" %}active{% endif %}"
               href="{% url "users:logout" %}">Выйти</a>
          </li>
          <liclass="nav-item">
          <a class="nav-link {% if view_name  == "posts:profile/user.authenticated" %}active{% endif %}"
             a
             href="{% url "posts:profile" user.username %}"> Пользователь: {{ user.username }}.</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == "users:login" %}active{% endif %}"
             href="{% url "users:login" %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == "singup" %}active{% endif %}"
             href="{% url "users:signup" %}">Регистрация</a>
        </li>
      {% endif %}
    {% endwith %}
  </ul>
</div>
</nav>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/includes/post_card.html
{% load thumbnail %}
<ul>
  {% if show_author %}
  <li>
    <a href="{% url "posts:profile" post.author %}" role="button">{{ post.author.get_full_name }}</a>
  </li>
  {% endif %}
  <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
</ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
<p>
  {{ post.text|linebreaksbr }}
</p>
{% if show_post%}
<a a
   class="btn btn-sm btn-secondary rounded"
   href="{% url 'posts:post_detail' post.id %}"
   role="button"> Подробная информация </a>
{% endif%}
{% if show_group and post.group %}
  <a a
     class="btn btn-sm btn-secondary rounded"
     href="{% url 'posts:group_list' post.group.slug %}"
     role="button">Все записи группы</a>
{% endif %}
{% if user == post.author %}
  <a class="btn btn-sm btn-secondary rounded"
     href="{% url 'posts:post_edit' post.id %}"
     role="button">Редактировать</a>
{% endif %}

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}